---
tiers:
    -
        name: samples
        description: ''
        testcases:
            -
                case_name: first
                project_name: xtesting
                criteria: 100
                blocking: true
                clean_flag: false
                description: ''
                run:
                    name: 'first'

            -
                case_name: second
                project_name: xtesting
                criteria: 100
                blocking: true
                clean_flag: false
                description: ''
                run:
                    name: 'second'

            -
                case_name: third
                project_name: xtesting
                criteria: 100
                blocking: true
                clean_flag: false
                description: ''
                run:
                    name: 'bashfeature'
                    args:
                        cmd: 'echo -n Hello World; exit 0'

            -
                case_name: fourth
                project_name: xtesting
                criteria: 100
                blocking: true
                clean_flag: false
                description: ''
                run:
                    name: 'unit'
                    args:
                        name: 'xtesting.samples.fourth'

            -
                case_name: fifth
                project_name: xtesting
                criteria: 100
                blocking: true
                clean_flag: false
                description: ''
                run:
                    name: 'robotframework'
                    args:
                        suites:
                            - /usr/lib/python3.8/site-packages/xtesting/samples/HelloWorld.robot
                        variable:
                            - 'var01:foo'
                            - 'var02:bar'

            -
                case_name: sixth
                project_name: xtesting
                criteria: 100
                blocking: false
                clean_flag: false
                description: ''
                run:
                    name: 'behaveframework'
                    args:
                        suites:
                            - /usr/lib/python3.8/site-packages/xtesting/samples/features/
                        tags:
                            - foo
